-- MySQL Script generated by MySQL Workbench
-- Sun Dec 11 22:08:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TrenesArgentinos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrenesArgentinos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrenesArgentinos` DEFAULT CHARACTER SET utf8 ;
USE `TrenesArgentinos` ;

-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `contraseña` CHAR(60) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Genero` (
  `idGenero` INT UNSIGNED NOT NULL,
  `Genero` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Nacionalidad` (
  `IdNacionalidad` INT UNSIGNED NOT NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `Gentilicio` VARCHAR(45) NULL,
  `isoPais` TINYINT(5) NULL,
  PRIMARY KEY (`IdNacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`tipoDNI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`tipoDNI` (
  `idtipoDNI` INT UNSIGNED NOT NULL,
  `tipoDN` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoDNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Pasajeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Pasajeros` (
  `idPasajero` INT UNSIGNED NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT UNSIGNED NOT NULL,
  `Genero_idGenero` INT UNSIGNED NOT NULL,
  `Nacionalidad_IdNacionalidad` INT UNSIGNED NOT NULL,
  `tipoDNI_idtipoDNI` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPasajero`, `Genero_idGenero`, `Nacionalidad_IdNacionalidad`, `tipoDNI_idtipoDNI`),
  INDEX `fk_Pasajeros_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Pasajeros_Genero1_idx` (`Genero_idGenero` ASC) VISIBLE,
  INDEX `fk_Pasajeros_Nacionalidad1_idx` (`Nacionalidad_IdNacionalidad` ASC) VISIBLE,
  INDEX `fk_Pasajeros_tipoDNI1_idx` (`tipoDNI_idtipoDNI` ASC) VISIBLE,
  CONSTRAINT `fk_Pasajeros_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `TrenesArgentinos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasajeros_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `TrenesArgentinos`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasajeros_Nacionalidad1`
    FOREIGN KEY (`Nacionalidad_IdNacionalidad`)
    REFERENCES `TrenesArgentinos`.`Nacionalidad` (`IdNacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasajeros_tipoDNI1`
    FOREIGN KEY (`tipoDNI_idtipoDNI`)
    REFERENCES `TrenesArgentinos`.`tipoDNI` (`idtipoDNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Tren`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Tren` (
  `idTren` INT NOT NULL,
  `Locomotora` VARCHAR(45) NULL,
  PRIMARY KEY (`idTren`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Vagon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Vagon` (
  `idVagon` INT NOT NULL,
  `Tren_idTren` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idVagon`, `Tren_idTren`, `Categoria_idCategoria`),
  INDEX `fk_Vagon_Tren1_idx` (`Tren_idTren` ASC) VISIBLE,
  INDEX `fk_Vagon_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Vagon_Tren1`
    FOREIGN KEY (`Tren_idTren`)
    REFERENCES `TrenesArgentinos`.`Tren` (`idTren`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vagon_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `TrenesArgentinos`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`EstadoAsiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`EstadoAsiento` (
  `idEstadoAsiento` INT NOT NULL,
  `Asiento` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoAsiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Asiento` (
  `idAsiento` INT NOT NULL,
  `Vagon_idVagon` INT NOT NULL,
  `Asiento` INT NULL,
  `EstadoAsiento_idEstadoAsiento` INT NOT NULL,
  PRIMARY KEY (`idAsiento`, `Vagon_idVagon`, `EstadoAsiento_idEstadoAsiento`),
  INDEX `fk_Asiento_Vagon1_idx` (`Vagon_idVagon` ASC) VISIBLE,
  INDEX `fk_Asiento_EstadoAsiento1_idx` (`EstadoAsiento_idEstadoAsiento` ASC) VISIBLE,
  CONSTRAINT `fk_Asiento_Vagon1`
    FOREIGN KEY (`Vagon_idVagon`)
    REFERENCES `TrenesArgentinos`.`Vagon` (`idVagon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asiento_EstadoAsiento1`
    FOREIGN KEY (`EstadoAsiento_idEstadoAsiento`)
    REFERENCES `TrenesArgentinos`.`EstadoAsiento` (`idEstadoAsiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`MetodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`MetodoPago` (
  `idMetodoPago` INT UNSIGNED NOT NULL,
  `MetodoPago` VARCHAR(45) NULL,
  PRIMARY KEY (`idMetodoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Venta` (
  `Pasajeros_idPasajero` INT UNSIGNED NOT NULL,
  `IdVenta` INT NOT NULL,
  `FechaEmision` DATETIME NULL,
  `MetodoPago_idMetodoPago` INT UNSIGNED NOT NULL,
  INDEX `fk_Venta_Pasajeros1_idx` (`Pasajeros_idPasajero` ASC) VISIBLE,
  PRIMARY KEY (`IdVenta`, `Pasajeros_idPasajero`, `MetodoPago_idMetodoPago`),
  INDEX `fk_Venta_MetodoPago1_idx` (`MetodoPago_idMetodoPago` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Pasajeros1`
    FOREIGN KEY (`Pasajeros_idPasajero`)
    REFERENCES `TrenesArgentinos`.`Pasajeros` (`idPasajero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_MetodoPago1`
    FOREIGN KEY (`MetodoPago_idMetodoPago`)
    REFERENCES `TrenesArgentinos`.`MetodoPago` (`idMetodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Estacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Estacion` (
  `idEstacion` INT NOT NULL,
  `Estacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Precio` (
  `idPrecio` INT UNSIGNED NOT NULL,
  `Precio` DECIMAL(8,2) NULL,
  `Estacion Origen` INT NOT NULL,
  `Estacion Destino` INT NOT NULL,
  PRIMARY KEY (`idPrecio`),
  INDEX `fk_Precio_Estacion1_idx` (`Estacion Origen` ASC) VISIBLE,
  INDEX `fk_Precio_Estacion2_idx` (`Estacion Destino` ASC) VISIBLE,
  CONSTRAINT `fk_Precio_Estacion1`
    FOREIGN KEY (`Estacion Origen`)
    REFERENCES `TrenesArgentinos`.`Estacion` (`idEstacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Precio_Estacion2`
    FOREIGN KEY (`Estacion Destino`)
    REFERENCES `TrenesArgentinos`.`Estacion` (`idEstacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Pasajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Pasajes` (
  `IdPasaje` INT NOT NULL,
  `NumeroPasaje` VARCHAR(45) NULL,
  `Venta_IdVenta` INT NOT NULL,
  `Asiento_idAsiento` INT NOT NULL,
  `Asiento_Vagon_idVagon` INT NOT NULL,
  `Asiento_EstadoAsiento_idEstadoAsiento` INT NOT NULL,
  `Precio_idPrecio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdPasaje`, `Venta_IdVenta`, `Asiento_idAsiento`, `Asiento_Vagon_idVagon`, `Asiento_EstadoAsiento_idEstadoAsiento`, `Precio_idPrecio`),
  UNIQUE INDEX `NumeroPasaje_UNIQUE` (`NumeroPasaje` ASC) VISIBLE,
  INDEX `fk_Pasajes_Venta1_idx` (`Venta_IdVenta` ASC) VISIBLE,
  INDEX `fk_Pasajes_Asiento1_idx` (`Asiento_idAsiento` ASC, `Asiento_Vagon_idVagon` ASC, `Asiento_EstadoAsiento_idEstadoAsiento` ASC) VISIBLE,
  INDEX `fk_Pasajes_Precio1_idx` (`Precio_idPrecio` ASC) VISIBLE,
  CONSTRAINT `fk_Pasajes_Venta1`
    FOREIGN KEY (`Venta_IdVenta`)
    REFERENCES `TrenesArgentinos`.`Venta` (`IdVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasajes_Asiento1`
    FOREIGN KEY (`Asiento_idAsiento` , `Asiento_Vagon_idVagon` , `Asiento_EstadoAsiento_idEstadoAsiento`)
    REFERENCES `TrenesArgentinos`.`Asiento` (`idAsiento` , `Vagon_idVagon` , `EstadoAsiento_idEstadoAsiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasajes_Precio1`
    FOREIGN KEY (`Precio_idPrecio`)
    REFERENCES `TrenesArgentinos`.`Precio` (`idPrecio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Horario` (
  `Tren_idTren` INT NOT NULL,
  `Estacion_idEstacion` INT NOT NULL,
  `Horario` DATETIME NULL,
  PRIMARY KEY (`Tren_idTren`, `Estacion_idEstacion`),
  INDEX `fk_Tren_has_Estacion_Estacion1_idx` (`Estacion_idEstacion` ASC) VISIBLE,
  INDEX `fk_Tren_has_Estacion_Tren1_idx` (`Tren_idTren` ASC) VISIBLE,
  CONSTRAINT `fk_Tren_has_Estacion_Tren1`
    FOREIGN KEY (`Tren_idTren`)
    REFERENCES `TrenesArgentinos`.`Tren` (`idTren`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tren_has_Estacion_Estacion1`
    FOREIGN KEY (`Estacion_idEstacion`)
    REFERENCES `TrenesArgentinos`.`Estacion` (`idEstacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Ramal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Ramal` (
  `idRamal` INT UNSIGNED NOT NULL,
  `Ramal` VARCHAR(45) NULL,
  PRIMARY KEY (`idRamal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrenesArgentinos`.`Ramal_has_Estacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrenesArgentinos`.`Ramal_has_Estacion` (
  `Ramal_idRamal` INT UNSIGNED NOT NULL,
  `Estacion_idEstacion` INT NOT NULL,
  PRIMARY KEY (`Ramal_idRamal`, `Estacion_idEstacion`),
  INDEX `fk_Ramal_has_Estacion_Estacion1_idx` (`Estacion_idEstacion` ASC) VISIBLE,
  INDEX `fk_Ramal_has_Estacion_Ramal1_idx` (`Ramal_idRamal` ASC) VISIBLE,
  CONSTRAINT `fk_Ramal_has_Estacion_Ramal1`
    FOREIGN KEY (`Ramal_idRamal`)
    REFERENCES `TrenesArgentinos`.`Ramal` (`idRamal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ramal_has_Estacion_Estacion1`
    FOREIGN KEY (`Estacion_idEstacion`)
    REFERENCES `TrenesArgentinos`.`Estacion` (`idEstacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
